# Generated by Django 5.0 on 2024-02-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttestmodel',
            name='doctor',
        ),
    ]
