# Generated by Django 5.0 on 2024-02-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalTest', '0002_remove_patienttestmodel_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientTestModel',
        ),
    ]
