# Generated by Django 5.0 on 2024-01-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodel',
            name='image',
        ),
    ]
