# Generated by Django 5.0 on 2024-01-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patientmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='mobile_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
