# Generated by Django 5.0 on 2024-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelistmodel',
            name='strength',
            field=models.CharField(max_length=100),
        ),
    ]
