# Generated by Django 5.0 on 2024-02-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicinelistmodel_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelistmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
