# Generated by Django 5.0 on 2024-02-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicinelistmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buymedicinemodel',
            name='doctor',
        ),
    ]
