# Generated by Django 5.0 on 2024-01-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctormodel_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=1000000000000, max_length=12),
        ),
    ]
