# Generated by Django 5.0 on 2024-01-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctormodel_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='balance',
        ),
    ]
